languages = (
    ('1c', '1C'),
    ('abnf', 'ABNF'),
    ('accesslog', 'Access logs'),
    ('ada', 'Ada'),
    ('armasm', 'ARM assembler'),
    ('avrasm', 'AVR assembler'),
    ('actionscript', 'ActionScript'),
    ('alan', 'Alan'),
    ('angelscript', 'AngelScript'),
    ('apache', 'Apache'),
    ('applescript', 'AppleScript'),
    ('arcade', 'Arcade'),
    ('asciidoc', 'AsciiDoc'),
    ('aspectj', 'AspectJ'),
    ('autohotkey', 'AutoHotkey'),
    ('autoit', 'AutoIt'),
    ('awk', 'Awk'),
    ('axapta', 'Axapta'),
    ('bash', 'Bash'),
    ('basic', 'Basic'),
    ('bnf', 'BNF'),
    ('brainfuck', 'Brainfuck'),
    ('cs', 'C#'),
    ('cpp', 'C++'),
    ('cal', 'C/AL'),
    ('cos', 'Cache Object Script'),
    ('cmake', 'CMake'),
    ('coq', 'Coq'),
    ('csp', 'CSP'),
    ('css', 'CSS'),
    ('capnproto', 'Cap’n Proto'),
    ('clojure', 'Clojure'),
    ('coffeescript', 'CoffeeScript'),
    ('crmsh', 'Crmsh'),
    ('crystal', 'Crystal'),
    ('cypher', 'Cypher (Neo4j)'),
    ('d', 'D'),
    ('dns', 'DNS Zone file'),
    ('dos', 'DOS'),
    ('dart', 'Dart'),
    ('delphi', 'Delphi'),
    ('diff', 'Diff'),
    ('django', 'Django'),
    ('dockerfile', 'Dockerfile'),
    ('dsconfig', 'dsconfig'),
    ('dts', 'DTS (Device Tree)'),
    ('dust', 'Dust'),
    ('dylan', 'Dylan'),
    ('ebnf', 'EBNF'),
    ('elixir', 'Elixir'),
    ('elm', 'Elm'),
    ('erlang', 'Erlang'),
    ('excel', 'Excel'),
    ('extempore', 'Extempore'),
    ('fsharp', 'F#'),
    ('fix', 'FIX'),
    ('fortran', 'Fortran'),
    ('gcode', 'G-Code'),
    ('gams', 'Gams'),
    ('gauss', 'GAUSS'),
    ('godot', 'GDScript'),
    ('gherkin', 'Gherkin'),
    ('gn', 'GN for Ninja'),
    ('go', 'Go'),
    ('gf', 'Grammatical Framework'),
    ('golo', 'Golo'),
    ('gradle', 'Gradle'),
    ('groovy', 'Groovy'),
    ('xml', 'HTML, XML'),
    ('http', 'HTTP'),
    ('haml', 'Haml'),
    ('handlebars', 'Handlebars'),
    ('haskell', 'Haskell'),
    ('haxe', 'Haxe'),
    ('hy', 'Hy'),
    ('ini', 'Ini, TOML'),
    ('inform7', 'Inform7'),
    ('irpf90', 'IRPF90'),
    ('json', 'JSON'),
    ('java', 'Java'),
    ('javascript', 'JavaScript'),
    ('kotlin', 'Kotlin'),
    ('leaf', 'Leaf'),
    ('lasso', 'Lasso'),
    ('less', 'Less'),
    ('ldif', 'LDIF'),
    ('lisp', 'Lisp'),
    ('livecodeserver', 'LiveCode Server'),
    ('livescript', 'LiveScript'),
    ('lua', 'Lua'),
    ('makefile', 'Makefile'),
    ('markdown', 'Markdown'),
    ('mathematica', 'Mathematica'),
    ('matlab', 'Matlab'),
    ('maxima', 'Maxima'),
    ('mel', 'Maya Embedded Language'),
    ('mercury', 'Mercury'),
    ('mirc', 'mIRC Scripting Language'),
    ('mizar', 'Mizar'),
    ('mojolicious', 'Mojolicious'),
    ('monkey', 'Monkey'),
    ('moonscript', 'Moonscript'),
    ('n1ql', 'N1QL'),
    ('nsis', 'NSIS'),
    ('nginx', 'Nginx'),
    ('nimrod', 'Nimrod'),
    ('nix', 'Nix'),
    ('ocaml', 'OCaml'),
    ('objectivec', 'Objective C'),
    ('glsl', 'OpenGL Shading Language'),
    ('openscad', 'OpenSCAD'),
    ('ruleslanguage', 'Oracle Rules Language'),
    ('oxygene', 'Oxygene'),
    ('pf', 'PF'),
    ('php', 'PHP'),
    ('parser3', 'Parser3'),
    ('perl', 'Perl'),
    ('plaintext', 'Plaintext: no highlight'),
    ('pony', 'Pony'),
    ('pgsql', 'PostgreSQL, PL/pgSQ'),
    ('powershell', 'PowerShell'),
    ('processing', 'Processing'),
    ('prolog', 'Prolog'),
    ('properties', 'Properties'),
    ('protobuf', 'Protocol Buffers'),
    ('puppet', 'Puppet'),
    ('python', 'Python'),
    ('profile', 'Python profiler results'),
    ('k', 'Q'),
    ('qml', 'QML'),
    ('r', 'R'),
    ('cshtml', 'Razor CSHTML'),
    ('reasonml', 'ReasonML'),
    ('rib', 'RenderMan RIB'),
    ('rsl', 'RenderMan RSL'),
    ('graph', 'Roboconf'),
    ('robot', 'Robot Framework'),
    ('rpm-specfile', 'RPM spec files'),
    ('ruby', 'Ruby'),
    ('rust', 'Rust'),
    ('SAS', 'SAS'),
    ('scss', 'SCSS'),
    ('sql', 'SQL'),
    ('p21', 'STEP Part 21'),
    ('scala', 'Scala'),
    ('scheme', 'Scheme'),
    ('scilab', 'Scilab'),
    ('shexc', 'Shape Expressions'),
    ('shell', 'Shell'),
    ('smali', 'Smali'),
    ('smalltalk', 'Smalltalk'),
    ('solidity', 'Solidity'),
    ('stan', 'Stan'),
    ('stata', 'Stata'),
    ('iecst', 'Structured Text'),
    ('stylus', 'Stylus'),
    ('subunit', 'SubUnit'),
    ('supercollider', 'Supercollider'),
    ('swift', 'Swift'),
    ('tcl', 'Tcl'),
    ('terraform', 'Terraform (HCL)'),
    ('tap', 'Test Anything Protocol'),
    ('tex', 'TeX'),
    ('thrift', 'Thrift'),
    ('tp', 'TP'),
    ('twig', 'Twig'),
    ('typescript', 'TypeScript'),
    ('vbnet', 'VB.Net'),
    ('vbscript', 'VBScript'),
    ('vhdl', 'VHDL'),
    ('vala', 'Vala'),
    ('verilog', 'Verilog'),
    ('vim', 'Vim Script'),
    ('x86asm', 'x86 Assembly'),
    ('xl', 'XL'),
    ('xquery', 'XQuery'),
    ('yml', 'YAML'),
    ('zephir', 'Zephir')
)